# Generated by Django 3.2.9 on 2023-08-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleProblemNumber', models.IntegerField()),
                ('articleProblemLevel', models.IntegerField()),
                ('articleProblemLanguage', models.CharField(max_length=8)),
                ('articleProblemTrial', models.IntegerField()),
                ('articleTime', models.DateTimeField(verbose_name='date published')),
                ('articleSolvingTime', models.IntegerField()),
                ('articleNote', models.CharField(max_length=500)),
            ],
        ),
    ]
